### PR TITLE
Adding Unholy touch and moving unholy resolve to level three

### PR DESCRIPTION
**Pull request by TheDiggie**
-Moving unholy resolve up to level three to compete with holy resolve

-Adding unholy touch for the simple reason that theres no reason not to

-All these other files are just space and tab clean ups

### CODE REVIEW

**Comment by M59lost** [comment]
Acid Touch is the Unholy touch. There is no need for Unholy touch. And Do not remove Unholy resolve from level one its the easiest spell to imp. All in all FAIL

**Comment by Daenks** [comment]
@M59lost same thing for the 3rd time. Comments need to add to the conversation. "Fail" not acceptable.

**Comment by tsShergill** [comment]
I am all for adding Unholy Touch into the game as a low level Qor spell as a low reagent cost alternative to Acid Touch. I don't see the harm in giving Qor users another "flavor" of attack. Faren has ice and fire attacks that both have advantages and disadvantages. Users that want a more powerful attack can use Acid. For someone who is building and wants to use something that doesn't cost as much mana and reagents can use Unholy.

I haven't looked at this pull yet. I also have artwork created for this spell if anyone is interested.

**Comment by skittles1** [comment]
@tsShergill Diggie used the code/graphics from #727 for this, so thank you :) By the way, I did a quick mockup of a switchable UI theme using your dark background bitmaps here if you're interested: https://github.com/skittles1/Meridian59_103/tree/darkUI

It's rebased for 103 but would need cleaning up before use.

**Comment by TheDiggie** [comment]
@tsShergill Yes Taran I used your code and graphics, seen you weren't working on it figured I finish it.  Players like new spells :P

**Comment by tsShergill** [comment]
@skittles1 Thanks for doing that! I'll be sure to check it out. :)

**Pull request closed without merging**
