### PR TITLE
Add ternary conditional operator to kod.

### PR DESCRIPTION
**Pull request by skittles1**
Adds the C-style ? : ternary operator to the kod language. Works the same as the C version - doesn't evaluate the 3rd expression if the condition is true, can be nested etc. Can also be used with the syntax x = y ? : z; to assign y to x if y is true.

### CODE REVIEW

**Comment by treymd** [comment]
Not wanted, and BTW this is like the millionth time you've decided things need to be added and completely ignored what everyone else has to say about it.  My beer has spoken.

**Comment by cyberjunk** [comment]
I like ternary operators, what's wrong with them ?
Expressions using them just "look" soo much cleaner IMO...
However have to admit it's one more thing you gotta learn (however you have to sooner than later anyways as dev)

**Comment by skittles1** [comment]
Keen I haven't ignored what anyone has said, the only reason this pull request is still open is because I wanted to ask Daenks why he doesn't want it. His reasons are probably the same as yours but if they aren't, it would be useful for me to know what they are.

I don't see how
```
if value
{
   piPreferences = piPreferences | CF_TEMPSAFE;
}
else
{
   piPreferences = piPreferences & ~CF_TEMPSAFE;
}
```
is any easier or harder to understand compared to
```
piPreferences = value ? piPreferences | CF_TEMPSAFE
                      : piPreferences & ~CF_TEMPSAFE;
```
but I'll accept that the conditional operator is of less value here if you guys are adamant about it.

Conditional operator would also allow simplifications like
```
if (piFlags & PFLAG_ANONYMOUS)
{
   if cap
   {
      rName = user_cap_someone_string;
   }
   else
   {
      rName = user_someone_string;
   }

   return rName;
}
```
to
```
if (piFlags & PFLAG_ANONYMOUS)
{
   return cap ? user_cap_someone_string : user_someone_string;
}
```
which I thought would be useful and was the main reason I wanted it.

**Comment by treymd** [comment]
KOD should be kept as simple as possible while providing as much functionality as possible.  The ternary operator does not add any functionality.  It seems a few people believe it is cleaner looking and more simplified than an if/else statement that performs the same task.  I've read enough code to know that is a minority opinion, most people choose to use if/else rather than the ternary operator, though I do see it in the wild a small number of times.

We all understand what it means and how to use it.  That being said, it doesn't really matter what Shak, Delerium, Daenks, or I think about it, it matters what future KOD scripters will have to encounter when trying to add to the game.  Changes to the language are not something to take lightly and the target audience needs to considered.

**Comment by Daenks** [comment]
I agree with @treymd on this one guys. Lets keep kod simple where prudent, and this is one of those instances. 

If we want a more powerful game code language then lets switch to a more established one, not re-write kod from the ground up.

**Comment by cyberjunk** [comment]
>> It seems a few people believe it is cleaner looking and more simplified than an if/else statement that performs the same task. I've read enough code to know that is a minority opinion

Nope, sorry. Can't agree here. At least the majority of any devs I know prefer writing in ternary operators, they aren't more powerful, true, but they simple increase "readability" of some expressions IMO.

>> If we want a more powerful game code language then lets switch to a more established one, not re-write kod from the ground up.

Again, I really can't agree. I would love to see the server ported to another framework, but let's be honest, it's not gonna happen. So I basically welcome any change improving KOD...

**Pull request closed without merging**
