### PR TITLE
Moving truth and spellbane to a more reasonable place

### PR DESCRIPTION
**Pull request by TheDiggie**

### CODE REVIEW

**Comment by TheDiggie** [comment]
This change is to both organize Jala and make two spells more usefull. Curedntly truth (the hinder spell for riija) is level one, being level one its sp cannot reach a useable level while wearing pvp appropriate gear. Moving this spell up two levels will help it compete with the so of riija spells. Spellbane is also being moved up two levels for similar reasons, the previous change to Jala's range makes this spell more effective on its own so moving it to level five (previously in three) so that this spells level will match its power and usefulness. Spellbane is more appropriately placed in level five. With these two moves Jala's spells per level will move from: 4,3,5,2,2,1 to a much better looking: 3,3,4,3,3,1.

**Comment by skittles1** [comment]
I assume when the hinder spells were written, Riija was less powerful and less used than it is now. As it stands Jala has a level 1 spell that can diminish the effectiveness of an entire school, which makes more sense in a higher level (and opens up space in level 1 for us to add something level appropriate). Spellbane, by virtue of affecting all spells, should be in a higher level than any of the hinder spells (i.e. level 5). Both changes make sense, especially when considering #1071.

**Comment by GarOfMeridian** [comment]
Riija doesn't really have much that is cast 'in battle', so Truth has never really been that useful. Riijas typically show up already illusionary formed and flec'd and what not. It helps against Dement or Forget in a way, but doesn't actually hinder their spellpower. It just causes a bit of fizzles. So 'hindering an entire school' isn't really an accurate assessment. Moving spells around in levels isn't something we've ever done before either, so it should be for very good cohesive school-redesign reasons. AKA the team going over the whole school with an idea of what we want out of it.

Spellbane also has some pretty severe mechanism issues. Players with 99 spellpower can just ignore it. I think all hinder spells and spellbane need to be completely redone. They're more annoying than they are effective.

**Comment by skittles1** [comment]
I think that's what Diggie is doing (school redesign) though afaik he's only pitched the idea to a few people (and some don't want to get involved in the inevitable arguments). His plans look solid to me so far. Regarding Riija, it's more cast-mid-fight friendly than it used to be due to cost reductions over the past year and I do see players casting spells/replacing purged ones during battle.

I agree the hinder spells likely need redoing and possibly Spellbane also, but I'm very interested to see the outcome of this pull combined with Diggie's other one in terms of how many people try to or successfully use these spells in PvP.

**Comment by TheDiggie** [comment]
The whole idea Gar is to get these spell to a place where people will use them. If Spellbane doesn't do anything to 99% spells then this pull wont effect anything, bc casting a spell that doesn't work is the same as never casting it. This will give us ingame knowledge about what the spells need to be both balanced and useful. This isn't the final decision for Jala (as in range probably wont stay at 12).
We need to see these things used in battle, not played with on local servers.

**Comment by GarOfMeridian** [comment]
Changing the range doesn't change whether people will use them. It's just trying to get Mirth and Melancholy back as mule spells as far as I've heard.

**Comment by TheDiggie** [comment]
1) don't need mirth/melancholy mules. we have scrolls and they work great
2) if it was to just effect mirth/melancholy then I would have changed the range on just mirth/melancholy
3) you shouldn't comment saying we have other goals for the pull other than the listed idea, I've seen the hinder spells used in pvp, range is to low. 

We need this pull to see how effective jala is, we have no idea if hinder spells are good bc no one uses them, Like i've stated before, This is to get people to use jala so that we may adjust to balance

**Comment by skittles1** [comment]
See #1107 for new pull request.

**Pull request closed without merging**
