### PR TITLE
lowering reg cost

### PR DESCRIPTION
**Pull request by TheDiggie**

### CODE REVIEW

**Comment by Maikeljr** [comment]
I'm down with lowering the cost of deathrift. Although I'd suggest naming this pull that.

**Comment by GarOfMeridian** [comment]
Can we try 4 before we try 2? Right now we're in a really decent place where Death Rift is a 'grumpy' powerful ability (as in, people use it, because it can do unique things, but they're not happy about it). That might be due to the cost.

**Comment by TheDiggie** [comment]
imo gar.  elusion is way better than DR and it cost two kriipa claws that u can buy for 240 shils on island.

Dafs u cannot buy and are sold for between 200-300 gold so DR cost 1200-1800 shils

its much more expensive and a shityer spell.

but if 4 makes everyone happy i have no issue with it

just consider what i stated

**Comment by GarOfMeridian** [comment]
I think we talked about this before a little bit, but I do think Elusion and Death Rift are not directly comparable despite having similarities. Elusion is kind of like having access to Town Portals. Elusion makes you walk places you want to go in the world, but then you can return to town at any time. That's pretty strong.

Death Rift lets you go anywhere but walk back. So the power is in things like showing up at CV/avar village/wherever instantly out of nowhere. Maybe the reason you personally might think it's useless is that you are not in the range of playstyles that want that ability. For evasion types / lone wolf types that don't have a guild (shield, PK, who knows) Death Rift is incredibly powerful. 

I think we also need to be wary of characters that have both Elusion and Death Rift. If Death Rift becomes too inexpensive, we start treading on old Shadow Rift farming territory, where a character can be at a farming spot and return to town to sell in a loop instantly. Death Rift out, Elusion back in. Suddenly everywhere is right next to Quintor.

**Comment by TheDiggie** [comment]
now all we need is approval

**Comment by skittles1** [comment]
Closing, this was merged into develop.

**Pull request closed without merging**
