### PR TITLE
Unholytouch

### PR DESCRIPTION
**Pull request by TheDiggie**
adding unholy touch to the game, servel people have asked for it, no one disapproves of it

### CODE REVIEW

**Comment by TheDiggie** [comment]
the purpose of moving unholy resolve, for those interested, is to compete with the resist power of holy resolve, holy resolve is level three giving more resist then unholy resolve (level one). this make holy weapon more powerful then unholy weapon. with that said, this is a balancing change. im sure it will be effective.

**Comment by GarOfMeridian** [comment]
I think it's pretty interesting that holy and unholy damage are primarily delivered through weapon enchantments. I've developed quite a bit of content on my end that uses that theme. Adding an unholy touch spell just because we can waters down interesting asymptotic design. i.e. unholy becomes "just another element."

**Comment by Daenks** [comment]
Not sure this one should have been merged yet. Have we done any analysis on how this will affect PvP/PvE ? our default answer on a PR that affects game balance needs to be "no" until all aspects considered. On top of all that, this would be a perfect change to side-line into a larger spell overhaul or balance overhaul.

**Comment by skittles1** [comment]
Diggie's the 4th dev to suggest/code the unholy touch spell (though he used Taran's code and graphics), The pros and cons of it have been weighed up many times already:
* Qor is an offensive school, which should have an attack available from level 1.
* Players might take all Qor spells at character creation but forget acid touch, now they can buy this one from Raza elder/Qor priestess.
* Cost is far lower than acid touch for a new player.
* Unholy damage lacks content in the game, compared to other damage types.
* Damage is lower than acid touch.
* Unholy touch damage based on karma, so newer players will inherently not try to kill mobs that give them positive karma because they can't damage them with this spell.
* A new fast-improving spell in level 1 allowed Unholy Resolve to change to level 3, a level which players still complain about being painful (coincidentally, most recent complaint was about 14 hours ago from Rikku on 103).
* While not useless in PvP, it doesn't really compare to acid touch. It's unique in that no resist ring protects against it, but I don't think it will be used any more than zap or holy touch are, and is intended to be a mostly PvE spell (same as holy touch).

**Comment by GarOfMeridian** [comment]
I don't know about any of those points really

* "Diggie's the 4th dev to suggest/code the unholy touch spell "

Yep, because it's symmetrical and low hanging fruit. Faren ice bolt spell. Holy splash spell. Dual wielding. I can throw out a million. But asymptotic design is often cooler and more interesting.

* "Qor is an offensive school, which should have an attack available from level 1."

Faren is an offensive school. Qor is actually an evil school themed about sacrifice and servitude for power. I'm not sure they'd give an attack to any initiate just for signing up. First you have to go around spreading Darkness, stimying hunters with Cloak, and rooting out the followers of Good with Detect Good.

* "Players might take all Qor spells at character creation but forget acid touch, now they can buy this one from Raza elder/Qor priestess."

At that level they can beat down mummies with anything, really. Buy mace fighting and use it to get reags to work to Qor 2. Why's an attack spell so special? Holy touch is level 2, and shal has no level 1 attack spell.

* "Cost is far lower than acid touch for a new player."

I feel like expense for power has always been a strong Qor theme

* "Unholy damage lacks content in the game, compared to other damage types."

Well hey lemme build it then, I've got a ton of uses for holy and unholy coming up and surely some of it will be useful enough to go in.  I **really** like where holy and unholy are at, because they're rare and interesting compared to fire/shock/ice/acid which might as well all be the same thing.

* "Unholy touch damage based on karma, so newer players will inherently not try to kill mobs that give them positive karma because they can't damage them with this spell."

Can't we emphasize Detect Good's use for that purpose?

* "A new fast-improving spell in level 1 allowed Unholy Resolve to change to level 3, a level which players still complain about being painful (coincidentally, most recent complaint was about 14 hours ago from Rikku on 103)."

I don't personally like that unnecessary level change, either. Qor is supposed to be difficult. That's part of its charm. And I definitely don't like that there is continued talk of using player complaints as easy fuel for design decisions, especially because these complaints are to you, and you will probably only report complaints that support your ideas and discard others. No personal attack intended. I think it's just human nature. You may be inclined to ignore mine, Gotti's, or Lost's complaints and forget you ever heard them really. We're probably just trolling, or so it seems. But you actually threatened to purposely build a list of complaints against some design metric of mine the other month and I thought well, of course it's going to say what you want in the end. It's a list that only has that kind of complaint. There's nobody to keep a list of the opposite side because there are no other admins. We don't really take player votes, either, so the entire concept is a bit dodgy.

* "While not useless in PvP, it doesn't really compare to acid touch. It's unique in that no resist ring protects against it, but I don't think it will be used any more than zap or holy touch are, and is intended to be a mostly PvE spell (same as holy touch)."

But I'm building content that works with unholy (and indirectly through all the other resists). And if not me, I'm sure somebody else will. It's going to be used if it has no / uncommon resists. This is a really cool situation for an element, and if unholy becomes readily available and symmetrical, I'll just have to add yet another element (like Chaos or something). Don't think I like that.

-------

If Unholy Touch goes in, it's not the end of the world. I think just the opposite, it won't really do anything at all. Unnecessary stuff that's thrown in just because someone thought of it makes us look a little silly.

I hope somebody does something cool with it. Don't put it at level one. Put Acid Touch down to level one if you MUST have a level one attack spell, then put unholy touch at level SIX qor. These are the utmost servants of Qor. Only then can you deal unholy damage directly. Shal is different; shal wants you to strike down the undead. Of course she'd give holy touch much sooner.

Have some quests surrounding it. Hell, make Unholy Touch (even if it's level one) available from someone in Biskalane who is lored as a keeper of ancient magics (some from our mainland). Why hasn't this spell been available all this time? Suddenly it just exists one day?

let's do more than just throw things in to make neat symmetry.

**Comment by TheDiggie** [comment]
Unholy touch is nessacary. 
Ive tested it agianst evil mobs and players. Even players with high karma unholy touch will not hit harder than even a mace. 

Its not for pvp

Everytime i build a qor i take holy touch and build hp first because acid touch does shit damage on almost everything

Qor needs a good spell to build with. Every starting school has a building skill except qor.

"I think it's pretty interesting that holy and unholy damage are primarily delivered through weapon enchantments, and that resistance to both elements is hard to come by."

Hate to be blunt but the statement is incredably false. Theres two types of holy damage and one unholy. 

Holy weapon
Holy touch
Unholy weapon.

Holy touch is way more effective use of holy damage the holy weapon. Ive been attacked by holy touch and holy bows. Ive used holy bows. Holy weapon is not worth the enchantment. Id sooner dedicate my bow to krannan. 

Resistances: unholy/holy resolve, both of these are extremly cheap and provide a lot of resistance to both karma attacks. Im not sure but resist magic may also resist it (if not i suggest making it resist it) 

Reason for moving unholy resolve is simple. Why should shal have a almost free 99 in level three? Shal'ille is overpowerd as it is. Moving the spell doesnt hurt anyone infact it helps them progress. 

-Diggie has spoken

**Comment by TheDiggie** [comment]
"Don't put it at level one. Put Acid Touch down to level one if you MUST have a level one attack spell, then put unholy touch at level SIX qor."

I would sooner delete the branch befor doing this

**Comment by GarOfMeridian** [comment]
* " Holy touch is way more effective use of holy damage the holy weapon."

Holy touch has a karma penalty modifier. Holy enchantments don't.

* "Holy weapon is not worth the enchantment. Id sooner dedicate my bow to krannan."

Kraanan dedications do not actually do anything in PvP, but Shal and Qor enchantments turn bow and weapon damage partially magical, allowing them to bypass a large degree of enemy armor. Partially magical attacks are also much more effective against Armor of Gort's capping mechanism. The difference is very large, most especially on heavily armored targets that are also using Gort.

For example, you might literally do 4-6 damage with a basic physical weapon against an opponent who has Gort, plate, a shield, a helm, and a full power Jonas shield (up to 11 armor). This is because Gort caps pure physical to 15, and then armor subtracts from there. Against that same opponent, a holy or unholy weapon will only be capped to 20, and subsequent armor will be halved (from Gort) or reduced by a third (general armor). So, because of a holy or unholy enchantment, you're looking at something like 13-17 damage rather than 4-6. That's a *huge* improvement, and it's awesome because it's not just crazy damage bonuses that would be overpowered elsewhere. It's a specific use of tools to cut through very strong defenses.

* "Resistances: unholy/holy resolve, both of these are extremly cheap and provide a lot of resistance to both karma attacks."

They are cheap, but not at all common. Any given player may only have one resistance at his disposal (since a player cannot cast Qor and Shal spells at the same time, and Holy and Unholy Resolve cannot be made into Jala potions), but any given player may wield Qor or Shal damage as the situation permits using weapon enchantments that have no karmic requirement.

Holy and Unholy Resolve provide up to 20% resistance to their respective elements, which is less than 25% for most other resistance buffs. This is something I did during the resistance rebalance to accentuate Holy and Unholy's rare status.

Resist Magic does resist holy and unholy damage (along with all other magic) by up to 25%. Its mitigating factor is that it does not last very long. It is also not a single solution to the situation described above; 13-17 cut by 25% is still 9-13, as compared to 3-4 without the enchantment. You're still doing reasonable damage rather than basically nothing.

* "Reason for moving unholy resolve is simple. Why should shal have a almost free 99 in level three?"

One of Shal's themes has always been that it is very cheap to work. Emeralds, herbs, and so on. Aside from that, why *shouldn't* Shal have an almost free 99 in level three? What is so pressing here that an unprecedented move in spell levels is required?

*" Everytime i build a qor i take holy touch and build hp first because acid touch does poor damage on almost everything."

That has not been my experience. Acid Touch is great for killing trees and lupoggs. Starting out Qor is very difficult due to lowbie monster karma and resistance distribution. I think that's also one of Qor's themes.

* "Qor needs a good spell to build with. Every starting school has a building skill except qor."

You could definitely rework lowbie monster acid resistances, which is part of an early game redesign we really need, instead of adding a new spell that only solves a problem for starting-out Qors.

**Comment by TheDiggie** [comment]
Well i wrote a big comment but my phone locked and decided to delete so. Short version. I highly disagree with 90% of this comment. Splash of acid does massive damage, vamp has no resist. Firball is trash.

**Comment by GarOfMeridian** [comment]
Splash of acid does not do "massive damage" - it does less than faren splash spells and can't be combined with mana focus.

**Comment by TheDiggie** [comment]
Gar. People have left meridian bc of how much damage my qor jala does. Soa does massive damage. Way more than shocking fury and explosive frost. Blast of fire can be argued. But it only hits hard due to the many types of -fire resist ingame. 

Theres litterly not one -cold item

**Pull request merged**
