### PR TITLE
Illusionary touch

### PR DESCRIPTION
**Pull request by TheDiggie**
-Same as illusionary wounds except in touch form copying the touch
attack spells

-Will be sold by the Riija Monk (level 2)

-Will require 1 firesand to cast

### CODE REVIEW

**Comment by PKChrisChan** [comment]
I love the idea. But illusionary damage is overwhelmingly powerful. It does damage and ignores all resist rings/resist magic. Add all the bless/rings/JoF bonuses. You are nuking your target 20-30 per sec even better than blast spells. it completely destroys PvE/PvP. 

Why build faren when you can build the same skill which ignore resists.

**Comment by skittles1** [comment]
Tend to agree with PKChrisChan here, it's unlikely we could enable this spell without nerfing it to make it less competitive with tof or acid touch. That said, when complete we should probably add it to the game but not allow it to be sold, might be able to use it eventually.

**Comment by TheDiggie** [comment]
Trust me I realize this, I already halved the bonus from jofs on ill touch. Further balancing cant be done till i'm sure the ill damage is working.

**Comment by PKChrisChan** [comment]
I would make it level 5 or 6. I would solely take it level 2 riija on every characters I make from then on. Simply for ignoring resists and destroying Pve.

**Comment by TheDiggie** [comment]
it hits trolls for2 so, good luck trying to pve with it

**Pull request closed without merging**
