### PR TITLE
Get Objects of a Class in a holder

### PR DESCRIPTION
**Pull request by GarOfMeridian**
This searches for objects of class cClass.

Only searches active by default. search_active = true

Set search_passive to TRUE to search passive objects.

### CODE REVIEW

**Comment by skittles1** [comment]
Just a note, depending on how often the code is called you'll want to still use a foreach loop in place rather than calling this message (especially the case for things in Monster, Room, Player or User that might run a lot).

**Comment by GarOfMeridian** [comment]
Why's that exactly? Is this more costly than a loop in place?

**Comment by skittles1** [comment]
Yes, for frequently called code we have to minimise the number of instructions as much as we can.

**Comment by skittles1** [comment]
On second thought this message probably shouldn't be added - the only reason to create a new list of the objects would be if you need to further delete or add elements to the list and do something with it at the end (e.g. this call could be used in the GetTargets() type code, which returns a list that may be modified). If we need a standard call to return a filtered list I would rather make a C call that we could wrap in an easy to use message (excuse the crappy name on the C call):
```
GetPlayers()
{
   return FilterSubListByClass(plActive, 1, &Player);
}
```
which would run in about 1-5% of the time the existing/proposed code does.

For code that just needs to send something to the object (MsgSendUser or whatever), we shouldn't create new list nodes to facilitate it - in that case an in-place foreach loop is the better option for the foreseeable future.

**Pull request closed without merging**
