### PR TITLE
thrasher upgrades

### PR DESCRIPTION
**Pull request by TheDiggie**
Remove enfeeble, it is nothing but aggervating. it serves no purpose.

Raised cashmin from -12000 to -9000. such tuff mobs shouldn't have such
a negative cash drop.

Made karma neutral so that qors may have a place to reach 150 without
destroing karma.

### CODE REVIEW

**Comment by Maikeljr** [comment]
I would love to see neutral karma and removing of Enfeeble. Those things are annoying as is. +1

**Comment by TheDiggie** [comment]
added emerald and red mushrooms to the thrasher loot drop.

these are important for mages to build with for touch of flame and/or holy touch

**Comment by Maikeljr** [comment]
Seems fair enough.

**Comment by PKChrisChan** [comment]
Absolutely! +1!

**Comment by TheDiggie** [comment]
returned thrashers to 75 karma.

Lore doesnt approve of evil mobs not effecting karma

**Pull request merged**
