### PR TITLE
Remove cast timer from CC defenses

### PR DESCRIPTION
**Pull request by TheDiggie**
As posted on the globe if you are caught unbuffed it is basically game over.
With no cast time u can quickly buff yourself and have a chance at safety or even defeating your attacker.

### CODE REVIEW

**Comment by GarOfMeridian** [comment]
I've always supported this idea. Would be great to see it implemented.

**Comment by tsShergill** [comment]
I'm also a supporter of this pull. Anything that speeds up PvP gameplay.

**Comment by tsShergill** [comment]
What would it take to get this approved?

**Comment by TheDiggie** [comment]
its already approved =p

**Comment by skittles1** [comment]
This is already live on 103 for testing and feedback (since we can modify these values in-game). This way we can determine if the values Diggie picked here are ideal or if they need modification, saving the trouble of waiting for an update and possibly making more than one merge.

So far I'm not sure anyone has noticed the difference.

**Comment by GarOfMeridian** [comment]
I'm not sure we have the pvp quantity to see the long-term effects of something like this for quite awhile. Its best help is in scenarios where a player has been caught unbuffed by an attacker and can actually EE/FA/DI themselves, something which wasn't really the case before.

Of course, one of the prerequisites for that is that the victim actually have those buffs, and that he's actually trying to survive/escape/fight back. I don't know if we've done the other meta work yet to really encourage builders to try. It's still so much easier (lazier) to just log off.

**Comment by TheDiggie** [comment]
Shals shouldt even be able to use invis rings imo

**Pull request merged**
