### PR TITLE
This is wear i think resistances should be

### PR DESCRIPTION
**Pull request by TheDiggie**
these are resistance changes decided by real life armor (u cant stab a guy in plate armor so plate gets thrust resist)

Chain is metal, which means it conducts heat and electricity.

### CODE REVIEW

**Comment by Maikeljr** [comment]
We're gonna have a long talk about these changes. I think a lot more has to be done to make this more balanced. You simply nerfed the better armors, which is a good starting point, but didn't really buff anything else. Scale/leather is still complete garbage and plate will still only be used to get pked in.

**Comment by Maikeljr** [comment]
Leather - Resist all 5% magic/weapons high defense rating no armor
Chain - Resist all 10% weapons 5% all magic weakness small armor no defense penalty
Scale - Resist all 10% weapons 5 % magic weakness medium armor small defense penalty
Neru - Resist all 10% magic 5% melee weapon weakness medium armor no defense penalty
Plate - Resist 15% weapons 10% all magic weakness high armor medium defense penalty
Robe Disciple - 5% magic resist High SP 10% all weapon weakness no armor or defense penalty
Robe - 5% magic resist Medium general SP 10% weapon weakness no armor defense penalty

We can specify resists around all we want, but we need a balanced base to work from. Neru mostly anti caster, might as well be weaker to mellee weapons instead of earthquake. 

If we go super broad like this we can nit pick problems as we see them instead of just deciding fire/bolt damage is always gonna be better then splash/cold.

Again, this is just a starting point, we can specify as we test.

**Comment by TheDiggie** [comment]
Making everything resist everything ad removing the defense penaltys is not the way to go

**Comment by Maikeljr** [comment]
Well you've given me no reason why it can't work. Currently you have 2 useful armors and everything else is a bunch of crap. You can't simply say "no" without any reasoning. I gave reasoning for my thesis. Explain yours.

**Comment by TheDiggie** [comment]
My reasoning is i dont approve of every armor resisting everything. Thats the only explanation needed

**Comment by Daenks** [comment]
No bickering on here. Everyone needs to logicallyand precisely state their opinions and the reasoning behind them. If you need to argue this out do it in game or in irc.

**Comment by Maikeljr** [comment]
image

Would this be more of a compromise?

**Comment by TheDiggie** [comment]
I dont like the idea of adding resist to evdrything to the armors. Making plate resist all pyshical damage would be a huge kistake

**Comment by Maikeljr** [comment]
The idea was to make it less complicated and more balanced, but I can understand that it's a HUGE change of how we play. The compromise would be leaning in that direction, but still more of what you are used to.

**Comment by Maikeljr** [comment]
image

**Comment by LadyofDarkness** [comment]
My personal opinion is.... 

1) Don't cater changes around what makes sense in real life, for example putting -20 fire on everything robe. The reason why the regular robes dont have -20 fire is because they are +10 not +20. things are done for balance, not to make things accurate to real life, because it is a game and balance is more important.

2) I don't see what is wrong with the current resists. Although something should have -20 cold. Maybe chain? Then that would balance chain out a tiny bit.

Making the high end items super complicated by adding tons of resists seems like bad idea to me.  I don't see any reason to change this stuff and make it more complicated... for what reason?

**Comment by LadyofDarkness** [comment]
If we were to change one or any, I think it's a better idea to discuss them one by one. Mass changes are always bad and super confusing and then all the current players are like, why did you do that... While 2 people, you guys are happy.

**Comment by Maikeljr** [comment]
I completely agree about making everything perfect for real life and focusing on balance.

But if you think current resists are balanced you are not even looking. No one PvPs in anything but chain/neru 99% of the time. Why is this? Because our current system is horribly flawed and imbalanced.

I would agree with small changes in any other system, but this needs to happen to make other armor options even remotely feasible. Of course this is something we need to test extensively before throwing it out, but saying only two people will be happy is simply wrong .

**Comment by LadyofDarkness** [comment]
I need some more high end PVP experience before I comment on the balance of all this stuff. Agreed on the armor though, Neru and Chain seem a bit too overpowered and scale and plate being a bit too underpowered.

**Comment by TheDiggie** [comment]
Honestly there basicly no difference between fire resist and cold resist. 

Blast of fire and Explosive frost do the same amount of damage and cost the exact same regs. 

The only reason u never see Ef is because everything is -fire. 

Just saying it makes no differnce if u add -10 fire or -10 cold. Same damage same regs

**Comment by Maikeljr** [comment]
Well fighting Ice / Fire Golems farming wands and magical weapons I disagree. Ice resistance doesn't work to well vs Fire Golems. Lets make these changes on 104 and see how it feels with the current armors.

**Comment by Daenks** [comment]
There is clearly a lot of work and discussion that needs to be done before we apply another package of changes that affects resistances. I'm going to remove this pull from our milestone, to allow discussion to occur without the impending threat of unwanted changes being applied to the game.

**Pull request closed without merging**
