### PR TITLE
Thrasher Chest Adjustment

### PR DESCRIPTION
**Pull request by TheDiggie**
Some items have absolutely terrible itemat's, so i have swaped them out with items worth the fight.

### CODE REVIEW

**Comment by M59Gar** [comment]
Seems mostly irrelevant given the broken state of Blood Inheritance, but purge nerudite swords don't exist in the game elsewhere as far as I know. Not gamebreaking if they are put in, but this seems a bit odd

**Comment by TheDiggie** [comment]
Gar, its simple. you go threw thrasher and get the chest, you dont want a shitty vertigo axe. We shouldn't count on players having 3-7 qors and the prism to use BI. Yes, purge nerudite swords do not exist in any way....UNTIL NOW =P

**Comment by M59Gar** [comment]
Yeah I get that players want more loot and more power for less effort. Given that you're a player, this seems motivated more by that desire than by any real design need.

And 3 qor mules and a prism isn't difficult to acquire at all.

**Comment by TheDiggie** [comment]
Getting a three sided prism from the chest is a rare shot in hell. The chest is supos to be a reward not garbage i dont code anything to benifit me ingame and advise you dont assume so agian.

**Pull request merged**
