### PR TITLE
Survival arena rooms that need to be removed due to abuse

### PR DESCRIPTION
**Pull request by TheDiggie**

### CODE REVIEW

**Comment by skittles1** [comment]
Current excluded RIDS on 103:
: INT 2600
: INT 2601
: INT 6
: INT 4
: INT 28
: INT 26
: INT 24
: INT 2508
: INT 2507
: INT 2504
: INT 578
: INT 2012
: INT 2010
: INT 379
: INT 378
: INT 377
: INT 112
: INT 111
: INT 108
: INT 2135
: INT 2113
: INT 589
: INT 38
: INT 39
: INT 830
: INT 201
: INT 203
: INT 380
: INT 2151
: INT 2602
: ]

**Comment by GarOfMeridian** [comment]
That's a ton of rooms, what's the abuse in question?

**Comment by TheDiggie** [comment]
abuse is one of three things
the room has safe spots allowing the user to afk for any given amount of time.
the room is to small to host a good survival instance.
or the rooms spawn locations restrict your access to the mobs

**Comment by GarOfMeridian** [comment]
Safe spots even from walk through walls?

**Comment by TheDiggie** [comment]
Unsure

**Pull request merged**
